
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: quote_editor_development


test:
  <<: *default
  database: quote_editor_test
  username: <%= ENV['POSTGRES_USER'] || 'postgres' %> # Default to 'postgres' if not set
  password: <%= ENV['POSTGRES_PASSWORD'] || 'postgres' %> # Default to 'postgres' if not set


production:
  <<: *default
  database: quote_editor_production
  username: quote_editor
  password: <%= ENV["QUOTE_EDITOR_DATABASE_PASSWORD"] %>
