name: Test Project
on: push
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout get code
        uses: actions/checkout@v4.1.1
      - name: Run tests
      env:
        RAILS_ENV: test
      run: bin/rails test:system
